import type { QuestionSpec } from '../../../types'

export const questions: QuestionSpec[] = [
  {
    id: 'mysql-02-index-001',
    type: 'single',
    difficulty: 2,
    tags: ['B+树'],
    stem: 'InnoDB 选择 B+ 树（而不是红黑树、B 树或哈希表）作为索引结构，最核心的原因是？',
    options: [
      { key: 'A', text: '非叶子节点不存数据使树更矮、磁盘 IO 更少，且叶子节点链表相连，天然支持范围查询与排序' },
      { key: 'B', text: '红黑树不支持排序，只能做等值查找' },
      { key: 'C', text: 'B+ 树把整行数据都存在非叶子节点里，从而省去了回表' },
      { key: 'D', text: '哈希索引无法等值查询，已被 InnoDB 完全禁用' },
    ],
    answers: ['A'],
    explanation: 'A 正确：数据按页读取，非叶子节点只存键和指针，一页容纳更多键、树更矮胖，千万级数据约 3 层；叶子链表让范围扫描顺链进行。B 错误：红黑树中序遍历有序、支持排序，问题在于二叉结构太高、IO 次数多；C 错误：B+ 树数据存在叶子节点，非叶子只存键，免回表靠的是覆盖索引；D 错误：哈希等值查询很快，InnoDB 还有自适应哈希，被限制的是范围与排序场景。',
  },
  {
    id: 'mysql-02-index-002',
    type: 'single',
    difficulty: 1,
    tags: ['聚簇索引', '回表'],
    stem: "user 表上有二级索引 idx_name(name)。执行 SELECT * FROM user WHERE name = 'tom'（name 值唯一）时，相比按主键查询，InnoDB 还要多做哪一步？",
    options: [
      { key: 'A', text: '没有额外步骤，二级索引叶子节点存的就是整行数据' },
      { key: 'B', text: '回表：先在 idx_name 的叶子节点拿到主键 id，再到聚簇索引里查整行' },
      { key: 'C', text: '全表扫描一遍，确认没有其他叫 tom 的行' },
      { key: 'D', text: '先重建一次 idx_name 索引再查询' },
    ],
    answers: ['B'],
    explanation: 'InnoDB 是索引组织表：聚簇索引（主键索引）的叶子存整行，二级索引的叶子只存"索引列 + 主键"。用 idx_name 找到 tom 后拿到主键，还要回聚簇索引再查一次整行数据，这就是回表；SELECT * 几乎必然回表，因此列少时可用覆盖索引优化。A 错误：叶子只有索引列和主键；C 错误：索引定位是精确查找，不需要全表确认；D 错误：索引是持久结构，查询不会触发重建。',
  },
  {
    id: 'mysql-02-index-003',
    type: 'single',
    difficulty: 1,
    tags: ['最左前缀'],
    stem: '存在联合索引 idx(a, b, c)。查询 WHERE b = 2 AND c = 3 的索引使用情况是？',
    options: [
      { key: 'A', text: '完整用到 a、b、c 三列' },
      { key: 'B', text: '用到 b、c 两列' },
      { key: 'C', text: '用不上该索引，因为不满足最左前缀（缺少 a）' },
      { key: 'D', text: '只用到 a 列' },
    ],
    answers: ['C'],
    explanation: '联合索引按"先 a 后 b 再 c"排序，跳过最左列 a 就无法定位，如同电话簿先按姓排序、只报名字查不到。B 错误：b、c 虽出现在 WHERE 里，但没有 a 这个入口，索引扫描无法利用其有序性；A、D 明显不符合最左前缀原则。若业务确有该查询，应单独建 idx(b, c)。',
  },
  {
    id: 'mysql-02-index-004',
    type: 'single',
    difficulty: 2,
    tags: ['覆盖索引'],
    stem: "已有二级索引 idx_name(name)。SELECT id, name FROM user WHERE name = 'tom' 不需要回表，原因是？",
    options: [
      { key: 'A', text: '因为 id 是主键，涉及主键的查询都不回表' },
      { key: 'B', text: '查询列（id、name）全部包含在 idx_name 中：叶子节点存着 name 和主键 id，直接返回即可，Extra 显示 Using index' },
      { key: 'C', text: '因为 name 的值唯一' },
      { key: 'D', text: '因为 InnoDB 自动把整行数据复制到了每棵二级索引里' },
    ],
    answers: ['B'],
    explanation: '覆盖索引指一次索引扫描就能拿到 SELECT 与 WHERE 需要的全部列：idx_name 的叶子节点存有 name 与主键 id，本查询要的恰好只有这两列，无需回聚簇索引，EXPLAIN 的 Extra 出现 Using index。A 错误：是否回表取决于所需列是否都在索引里，与是否用到主键无关；C 错误：唯一性与覆盖无关；D 错误：二级索引只存索引列 + 主键，复制整行会浪费空间并拖慢写入。',
  },
  {
    id: 'mysql-02-index-005',
    type: 'multiple',
    difficulty: 3,
    tags: ['索引失效'],
    stem: 'orders 表结构：create_time DATETIME 有索引 idx_ct；phone VARCHAR(20) 有索引 idx_phone；name VARCHAR(20) 有索引 idx_name；remark VARCHAR(200) 无索引。下列写法会导致相关索引失效（无法正常利用索引定位）的有？',
    options: [
      { key: 'A', text: 'WHERE YEAR(create_time) = 2026' },
      { key: 'B', text: 'WHERE phone = 13812345678（传入的是数字字面量）' },
      { key: 'C', text: "WHERE name LIKE '%tom'" },
      { key: 'D', text: "WHERE name LIKE 'tom%'" },
      { key: 'E', text: "WHERE name = 'tom' OR remark = 'x'" },
    ],
    answers: ['A', 'B', 'C', 'E'],
    explanation: 'A 失效：对列套函数，优化器无法用索引的有序性定位，等价于逐行计算；B 失效：varchar 列与数字比较发生隐式转换，相当于给列做 CAST，同样破坏索引定位；C 失效：前导模糊无法确定扫描起点，只能全索引甚至全表扫描；E 失效：OR 的一侧（remark）没有索引，为返回正确结果只能走全表扫描。D 不失效：tom% 是前缀匹配，可以确定扫描范围，EXPLAIN 的 type 为 range，属于可用索引的写法。',
  },
  {
    id: 'mysql-02-index-006',
    type: 'single',
    difficulty: 3,
    tags: ['联合索引'],
    stem: '列表页 SQL：WHERE user_id = ? AND status = ? ORDER BY create_time DESC LIMIT 20，三个条件都很常用。最合适的联合索引是？',
    options: [
      { key: 'A', text: 'idx(create_time, user_id, status)' },
      { key: 'B', text: 'idx(user_id, status, create_time)' },
      { key: 'C', text: 'idx(user_id) 和 idx(create_time) 两个单列索引' },
      { key: 'D', text: 'idx(status, user_id)，排序交给 filesort' },
    ],
    answers: ['B'],
    explanation: '联合索引设计口诀：等值条件列放前，ORDER BY 列紧跟其后。idx(user_id, status, create_time) 中前两列做等值过滤，在满足等值的前缀内 create_time 本身有序，排序可直接利用索引（Extra 无 filesort），并配合 LIMIT 提前终止扫描。A 错误：最左列 create_time 不在 WHERE 条件中，索引入口用不上；C 错误：两个单列索引通常只能用其一，排序仍需 filesort；D 错误：只建了过滤没建排序，ORDER BY 仍要额外排序，20 行的 LIMIT 下浪费明显。',
  },
  {
    id: 'mysql-02-index-007',
    type: 'code',
    difficulty: 2,
    tags: ['隐式转换', '索引失效'],
    stem: '观察下面的建表与查询：\n\n~~~sql\nCREATE TABLE t_user (\n  id    BIGINT PRIMARY KEY,\n  phone VARCHAR(20) NOT NULL,\n  KEY idx_phone (phone)\n);\nINSERT INTO t_user VALUES (1, \'13800000001\');\n\nEXPLAIN SELECT * FROM t_user WHERE phone = 13800000001;\n~~~\n\n关于这条查询，正确的说法是？',
    options: [
      { key: 'A', text: '正常走 idx_phone 等值查询，无需修改' },
      { key: 'B', text: "idx_phone 失效：列是 VARCHAR、传入数字发生隐式转换（相当于对列做 CAST），走全表扫描；应写成 WHERE phone = '13800000001'" },
      { key: 'C', text: 'MySQL 会自动为该数字创建一个临时索引' },
      { key: 'D', text: '直接报错，类型不匹配的 SQL 无法执行' },
    ],
    answers: ['B'],
    explanation: "字符串列与数字比较时，MySQL 会把列值转成数字（对列套函数），破坏了索引的有序定位能力，EXPLAIN 显示 type=ALL 全表扫描——表一大这条 SQL 就会拖垮线上。B 给出正确的修复方式：传参与列类型保持一致，写成字符串字面量。A 错误：隐式转换后索引不可用；C 错误：MySQL 没有这种机制；D 错误：类型不匹配不会报错，而是隐式转换，反而更隐蔽危险。",
  },
  {
    id: 'mysql-02-index-008',
    type: 'scenario',
    difficulty: 2,
    tags: ['索引失效', '慢SQL'],
    scenario: "线上 orders 表约 2000 万行，运营后台的\"当日订单导出\"接口超时。抓到的 SQL 是：\n\n~~~sql\nSELECT * FROM orders WHERE DATE(create_time) = CURDATE();\n~~~\n\nEXPLAIN 显示 type=ALL、rows 约 2000 万。create_time 上明明建了索引 idx_ct。",
    stem: '最合理的处置是？',
    options: [
      { key: 'A', text: '加一台大内存从库，把导出任务切到从库上跑' },
      { key: 'B', text: '改写为范围查询：create_time >= CURDATE() AND create_time < CURDATE() + INTERVAL 1 DAY，去掉列上的函数，让 idx_ct 以 range 方式生效' },
      { key: 'C', text: '用 FORCE INDEX(idx_ct) 强制走索引即可，SQL 不用改' },
      { key: 'D', text: '把 create_time 的类型改成 DATE，让函数不再必要' },
    ],
    answers: ['B'],
    explanation: "排查链路：慢 → EXPLAIN 发现 type=ALL → 有索引却不走 → 对索引列套了 DATE() 函数导致失效。正确做法是改写成 sargable（可用索引）的范围条件：函数移到常量一侧，create_time 本身不做运算，idx_ct 以 range 扫描当天区间，扫描量从 2000 万降到当天的行数。A 治标不治本，全表扫描只是换台机器继续慢；C 无效：FORCE INDEX 无法绕过\"列上套函数\"造成的不可定位；D 改动类型会丢失时分秒信息、影响全部存量业务，代价远超改一条 SQL。",
  },
  {
    id: 'mysql-02-index-009',
    type: 'scenario',
    difficulty: 2,
    tags: ['隐式转换', '索引失效'],
    scenario:
      '会员表 member 的 user_no 是 VARCHAR 并建了唯一索引。运营后台查询 `WHERE user_no = 10086`（前端传来的数字字面量）时接口超时，EXPLAIN 显示 type=ALL 全表扫描；把条件改成 `WHERE user_no = \'10086\'` 后毫秒级返回。',
    stem: '对这个现象的根因与工程化修复，最准确的是？',
    options: [
      { key: 'A', text: '字符串列与数字比较时 MySQL 会把列隐式转换成数字（等价于对索引列套 CAST），索引失效退化为全表扫描；修复是入参类型与列类型对齐（传字符串），并在代码层杜绝数值/字符串混用' },
      { key: 'B', text: '唯一索引坏了，DROP 后重建同一个索引即可恢复走索引' },
      { key: 'C', text: '把 user_no 列改成 BIGINT，让比较两边都是数字，一劳永逸' },
      { key: 'D', text: '在 user_no 上再建一个普通索引，优化器会自动选择能走的那种' },
    ],
    answers: ['A'],
    explanation:
      '隐式转换规则：字符串与数字比较时「字符串转数字」，于是对 user_no 每一行做 CAST——索引列被函数包裹，B+ 树无法定位，type=ALL。这与「列上套函数导致索引失效」同源。A 是根因修复；B 重建索引不改变失效机理；C 是重大 schema 变更：若业务号允许前导零/字母（如 "010086"、平台前缀），改 BIGINT 直接丢数据语义；D 再建索引同样被 CAST 挡住。经验法则：让比较两边的类型与列定义一致，是写 sargable SQL 的基本要求。',
  },
]
