import type { QuestionSpec } from '../../../types'

export const questions: QuestionSpec[] = [
  {
    id: 'mysql-01-sql-001',
    type: 'single',
    difficulty: 2,
    tags: ['JOIN'],
    stem: '已知两张表数据如下：\n\n~~~sql\n-- 表 a：id 取值为 1、2、3（共 3 行）\n-- 表 b：aid 取值为 1、1、3（共 3 行）\nSELECT a.id, b.aid\nFROM a\nLEFT JOIN b ON a.id = b.aid;\n~~~\n\n这条 LEFT JOIN 返回的结果集有多少行？',
    options: [
      { key: 'A', text: '3 行' },
      { key: 'B', text: '4 行' },
      { key: 'C', text: '6 行' },
      { key: 'D', text: '9 行' },
    ],
    answers: ['B'],
    explanation: 'LEFT JOIN 以左表为基准逐行匹配右表：a.id=1 在 b 中匹配到 2 行（aid=1 出现两次）；a.id=2 无匹配，右表补 NULL，仍保留 1 行；a.id=3 匹配 1 行，合计 4 行。A 是 INNER JOIN 的行数（3 行，丢掉了无匹配的行）；C 错误地以为先去重再相加；D 是不带 ON 条件的笛卡尔积（3 × 3 = 9 行），而 JOIN 的本质就是先笛卡尔积再按 ON 条件过滤。',
  },
  {
    id: 'mysql-01-sql-002',
    type: 'single',
    difficulty: 1,
    tags: ['GROUP BY', 'HAVING'],
    stem: '要求查出"平均分大于 80 的学生"，下列 SQL 中正确的是？',
    options: [
      { key: 'A', text: "SELECT sid FROM score WHERE AVG(score) > 80 GROUP BY sid" },
      { key: 'B', text: "SELECT sid FROM score GROUP BY sid HAVING AVG(score) > 80" },
      { key: 'C', text: "SELECT sid FROM score GROUP BY sid WHERE AVG(score) > 80" },
      { key: 'D', text: "SELECT sid, AVG(score) > 80 FROM score GROUP BY sid" },
    ],
    answers: ['B'],
    explanation: '过滤"组"必须用 HAVING：它执行在 GROUP BY 之后，可以使用 AVG 这类聚合函数。A 错在 WHERE 执行于分组之前，此时还没有"组"，不允许使用聚合函数；C 语法错误，WHERE 不能写在 GROUP BY 之后；D 只是 SELECT 出一个布尔表达式，并没有做过滤，会把所有学生都查出来。',
  },
  {
    id: 'mysql-01-sql-003',
    type: 'single',
    difficulty: 2,
    tags: ['子查询', 'EXISTS'],
    stem: '关于 IN 与 EXISTS 子查询，下列说法正确的是？',
    options: [
      { key: 'A', text: 'EXISTS 只判断子查询是否返回至少一行，找到第一条匹配即返回 true，常用于相关子查询' },
      { key: 'B', text: 'EXISTS 必须配合 SELECT * 使用，写 SELECT 1 会报语法错误' },
      { key: 'C', text: 'IN 子查询在任何场景下都比 EXISTS 慢' },
      { key: 'D', text: 'NOT IN 与 NOT EXISTS 语义完全等价，可以随意互换' },
    ],
    answers: ['A'],
    explanation: 'EXISTS 的语义是存在性判断：子查询只要返回至少一行即为真，通常会做成相关子查询（外层驱动、内层用索引探测），找到第一条就停止。B 错误：EXISTS 只关心结果集是否非空，SELECT 1 是惯用写法；C 错误：谁快取决于内外表数据量与索引情况，且 MySQL 8 的优化器会把 IN 改写成半连接，不存在"永远更慢"；D 错误：NOT IN 的子查询结果中只要有一个 NULL，整个条件恒为空，而 NOT EXISTS 不受 NULL 影响，二者语义并不等价。',
  },
  {
    id: 'mysql-01-sql-004',
    type: 'code',
    difficulty: 3,
    tags: ['执行顺序'],
    stem: '执行下面的 SQL 会发生什么？\n\n~~~sql\nSELECT user_id, SUM(amount) AS total\nFROM orders\nWHERE total > 100\nGROUP BY user_id;\n~~~',
    options: [
      { key: 'A', text: '正常执行，返回消费总额大于 100 的用户' },
      { key: 'B', text: '报错：Unknown column "total" in "where clause"' },
      { key: 'C', text: '正常执行，返回所有用户的分组结果' },
      { key: 'D', text: '报错：GROUP BY 后必须出现所有 SELECT 列' },
    ],
    answers: ['B'],
    explanation: 'SQL 的逻辑执行顺序是 FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT：WHERE 执行在 SELECT 之前，别名 total 此时尚未产生，所以报"Unknown column"。A、C 错在以为 SELECT 的别名对 WHERE 可见；D 错误：本题的报错与 GROUP BY 的列完备性无关（仅含聚合列与分组列的写法本身是合法的），真正的原因是执行顺序。正确写法是把过滤聚合结果的条件放进 HAVING。',
  },
  {
    id: 'mysql-01-sql-005',
    type: 'multiple',
    difficulty: 2,
    tags: ['NULL'],
    stem: '关于 MySQL 中 NULL 的处理，下列说法正确的有？',
    options: [
      { key: 'A', text: 'COUNT(*) 统计所有行数；COUNT(col) 不统计 col 为 NULL 的行' },
      { key: 'B', text: 'NULL = NULL 的结果是 TRUE，可以用等号比较两个 NULL' },
      { key: 'C', text: 'NULL 与任何值用 = 比较结果都是 NULL，不能用等号判断 NULL，应使用 IS NULL / IS NOT NULL' },
      { key: 'D', text: 'SUM(col) 会把 NULL 当作 0 参与求和' },
      { key: 'E', text: 'ORDER BY col ASC 时，NULL 排在最前面（MySQL 视其为最小值）' },
    ],
    answers: ['A', 'C', 'E'],
    explanation: 'A 正确：COUNT(*) 数行数，COUNT(col) 数"该列非 NULL"的行；C 正确：NULL 与任何值比较结果都是 NULL（三值逻辑），等号判断永远为假，必须用 IS NULL；E 正确：MySQL 中 ASC 排序 NULL 视为最小、排最前（可用 NULLS LAST 思路配合 IS NULL 字段调整）。B 错误：NULL = NULL 的结果是 NULL 而非 TRUE，不成立；D 错误：SUM/AVG 等聚合函数会忽略 NULL 行，而不是按 0 参与计算。',
  },
  {
    id: 'mysql-01-sql-006',
    type: 'single',
    difficulty: 1,
    tags: ['聚合函数'],
    stem: '执行下面的 SQL，返回结果是？\n\n~~~sql\nCREATE TABLE t_score (id INT PRIMARY KEY, score INT);\nINSERT INTO t_score VALUES (1, 90), (2, 80), (3, NULL), (4, 60);\n\nSELECT AVG(score) FROM t_score;\n~~~',
    options: [
      { key: 'A', text: '57.5，NULL 被当作 0 参与平均' },
      { key: 'B', text: '76.67，NULL 行被忽略，按 3 行平均' },
      { key: 'C', text: 'NULL，只要列里出现 NULL，AVG 就返回 NULL' },
      { key: 'D', text: '报错，AVG 不允许对含 NULL 的列计算' },
    ],
    answers: ['B'],
    explanation: 'AVG 忽略 NULL 行：(90 + 80 + 60) / 3 ≈ 76.67。A 错误：如果 NULL 当 0 参与应是 230 / 4 = 57.5，但聚合函数并不这样处理；C 错误：只有"所有行都是 NULL"时 SUM 才返回 NULL，AVG 同理，部分为 NULL 只是减少参与计算的行数；D 错误：聚合函数天然允许 NULL，没有任何报错。想让 NULL 记 0 分，应显式写 AVG(IFNULL(score, 0))。',
  },
  {
    id: 'mysql-01-sql-007',
    type: 'single',
    difficulty: 2,
    tags: ['字符串函数', '日期函数'],
    stem: '下列关于 MySQL 常用函数的说法，正确的是？',
    options: [
      { key: 'A', text: "CONCAT('a', NULL) 的结果是 'a'，NULL 会被自动忽略" },
      { key: 'B', text: "SUBSTRING('mysql', 2, 2) 的结果是 'ys'，字符串位置从 1 开始" },
      { key: 'C', text: "DATEDIFF('2026-09-25', '2026-09-28') 的结果是 3" },
      { key: 'D', text: "DATE_FORMAT(NOW(), '%Y-%m') 中 %Y 表示两位年份" },
    ],
    answers: ['B'],
    explanation: "SUBSTRING 位置从 1 开始：第 2 个字符是 y、取 2 个即 'ys'。A 错误：CONCAT 中任一参数为 NULL，整体结果就是 NULL，拼接场景常用 IFNULL(col, '') 兜底；C 错误：DATEDIFF 是第一个日期减第二个日期，25 减 28 等于 -3；D 错误：%Y 是四位年份，两位年份是 %y。另外注意：对列套函数会让该列上的索引失效，格式化尽量放在常量一侧或应用层做。",
  },
  {
    id: 'mysql-01-sql-008',
    type: 'scenario',
    difficulty: 3,
    tags: ['JOIN', 'COUNT'],
    scenario: '运营反馈"会员周报"里的下单用户数比 BI 口径多了一倍。你找到报表 SQL：\n\n~~~sql\nSELECT COUNT(u.id) AS user_cnt\nFROM user u\nLEFT JOIN orders o ON o.user_id = u.id\nWHERE o.created_at >= \'2026-09-22\';\n~~~\n\nuser 表 5 万行，orders 表 500 万行，一个用户通常有多笔订单。',
    stem: '根因判断与处置，正确的是？',
    options: [
      { key: 'A', text: 'LEFT JOIN 语义不对，改成 INNER JOIN 统计口径就准了' },
      { key: 'B', text: '根因是一对多 JOIN 导致用户被明细行撑成多行、COUNT(u.id) 重复计数；应改为 COUNT(DISTINCT u.id)，或先把 orders 按用户聚合再去 JOIN' },
      { key: 'C', text: '在 Java 里把查询结果用 Set 去重后再返回，SQL 不用动' },
      { key: 'D', text: '数字偏大说明 orders 表存在重复脏数据，先对 orders 做全表去重清理' },
    ],
    answers: ['B'],
    explanation: '排查链路：数字偏大 → 与 BI 口径对账确认是"用户数"被放大 → 检查 SQL 发现 JOIN 后按明细行计数 → 一对多 JOIN 不去重，COUNT(u.id) 数的是"JOIN 后的行数"而非"人数"。B 正确：数人用 COUNT(DISTINCT u.id)，或先对 orders 按用户 GROUP BY 聚合成子查询再 JOIN，从源头消除膨胀。A 错误：换成 INNER JOIN 不改变一对多膨胀，只是丢掉无订单用户；C 错误：治标不治本，结果集大时还有内存与分页风险；D 错误：一人多单是正常业务数据，不是脏数据，误诊会导致破坏性清理。',
  },
]
